### ISSUE TITLE
feature 상의 error

### ISSUE THREAD

**Issue by return0927** [w3bn00b/tanbang-cafeteria#2]
이 레포의 src/tCafeteria.py 가 정상작동하지 않는 것처럼 보입니다.

Code
`funcSc = tCafeteria.tCafeteria("G100000479", 'DAEJEON', 'MIDDLE')
response = [
    funcSc.parseCafeteria(),
    funcSc.parseSchedule()
]`

Response
`['1', '\n']
`

**Comment by w3bn00b** [comment]
죄송합니다
현제 수정중에 있습니다

**Comment by return0927** [comment]
https://github.com/return0927/tanbang-cafeteria
확인해주세요.
